import { execFileSync } from "node:child_process";
import { existsSync, lstatSync, realpathSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const DEFAULT_HANDOFF_FILE = "CODEX-HANDOFF.md";
const MAX_CHANGED_FILES = 200;
const MAX_DIFFSTAT_BYTES = 8 * 1024;

function normalizeTool(value) {
  if (!value) return undefined;
  if (["cc", "claude", "claude-code"].includes(value)) return "Claude Code";
  if (value === "codex") return "Codex";
  return value;
}

function generateHandoff(cwd, options = {}) {
  return renderHandoff(collectHandoffContext(cwd, options));
}

async function createHandoff(cwd, options = {}) {
  const content = generateHandoff(cwd, options);
  if (options.stdout) return { path: null, content };

  const target = resolveHandoffOutput(cwd, options.output);
  await prepareHandoffTarget(cwd, target, options.force);
  await writeFile(target, content, "utf8");
  return { path: target, content };
}

function collectHandoffContext(cwd, options = {}) {
  const git = collectGitContext(cwd, options);
  return {
    project: path.basename(path.resolve(cwd)) || ".",
    generatedAt: options.generatedAt ?? new Date().toISOString(),
    from: normalizeTool(options.handoffFrom),
    to: normalizeTool(options.handoffTo),
    git
  };
}

function collectGitContext(cwd, options = {}) {
  if (git(cwd, ["rev-parse", "--is-inside-work-tree"])?.trim() !== "true") {
    return { available: false, branch: undefined, changedFiles: [], diffStat: undefined, recentCommits: [] };
  }

  return {
    available: true,
    branch: currentBranch(cwd),
    changedFiles: changedFiles(cwd),
    diffStat: diffStat(cwd),
    recentCommits: recentCommits(cwd, options.recentCommits ?? 5)
  };
}

function currentBranch(cwd) {
  return git(cwd, ["branch", "--show-current"])?.trim()
    || git(cwd, ["rev-parse", "--abbrev-ref", "HEAD"])?.trim()
    || undefined;
}

function changedFiles(cwd) {
  const output = git(cwd, ["status", "--porcelain=v1", "--untracked-files=all"]);
  if (!output) return [];
  return output.trimEnd().split("\n").filter(Boolean).map((line) => {
    const status = line.slice(0, 2).trim() || line.slice(0, 2);
    return { status, path: line.slice(3) };
  });
}

function diffStat(cwd) {
  return git(cwd, ["diff", "--stat", "HEAD"])?.trim()
    || git(cwd, ["diff", "--stat"])?.trim()
    || undefined;
}

function recentCommits(cwd, count) {
  const output = git(cwd, ["log", "--oneline", `-${count}`]);
  if (!output) return [];
  return output.trimEnd().split("\n").filter(Boolean);
}

function renderHandoff(context) {
  const git = context.git;
  const lines = [
    "# AI Handoff",
    "",
    "Generated by ai-switch without reading raw chat, sessions, or file contents. Git-derived sections use branch/status/diff-stat/log metadata only.",
    "",
    "## Project Context",
    "",
    ...(context.from ? [`- from: ${context.from}`] : []),
    ...(context.to ? [`- to: ${context.to}`] : []),
    `- project: \`${context.project}\``,
    `- generated: \`${context.generatedAt}\``,
    `- branch: ${git.available && git.branch ? `\`${git.branch}\`` : "_not available_"}`,
    "",
    "## Changed Files",
    "",
    ...changedFileLines(git),
    "",
    "## Diff Summary",
    "",
    ...diffStatLines(git),
    "",
    "## Recent Commits",
    "",
    ...recentCommitLines(git),
    "",
    "## Goal",
    "",
    "- _Fill in the current objective._",
    "",
    "## Decisions",
    "",
    "- _Fill in decisions already made._",
    "",
    "## Open TODO",
    "",
    "- _Fill in remaining work._",
    "",
    "## How to Test",
    "",
    "- _Fill in commands or manual checks._",
    "",
    "## Known Risks",
    "",
    "- _Fill in risks, edge cases, and follow-up concerns._",
    "",
    "## Notes for Next Agent",
    "",
    "- _Fill in any context that is not derivable from git._",
    ""
  ];
  return `${lines.join("\n")}`;
}

function changedFileLines(git) {
  if (!git.available) return ["- _Git status not available._"];
  if (git.changedFiles.length === 0) return ["- _No changed files detected._"];
  const lines = git.changedFiles.slice(0, MAX_CHANGED_FILES).map((file) => `- \`${file.status}\` ${file.path}`);
  if (git.changedFiles.length > MAX_CHANGED_FILES) {
    lines.push(`- _…and ${git.changedFiles.length - MAX_CHANGED_FILES} more files (truncated)._`);
  }
  return lines;
}

function diffStatLines(git) {
  if (!git.available) return ["- _Git diff not available._"];
  if (!git.diffStat) return ["- _No diff summary available._"];
  if (Buffer.byteLength(git.diffStat) <= MAX_DIFFSTAT_BYTES) return ["```text", git.diffStat, "```"];
  return ["```text", git.diffStat.slice(0, MAX_DIFFSTAT_BYTES), "```", "", "_Diff summary truncated._"];
}

function recentCommitLines(git) {
  if (!git.available) return ["- _Git history not available._"];
  if (git.recentCommits.length === 0) return ["- _No recent commits found._"];
  return git.recentCommits.map((commit) => `- \`${commit}\``);
}

function resolveHandoffOutput(cwd, output = DEFAULT_HANDOFF_FILE) {
  return path.resolve(cwd, output);
}

async function prepareHandoffTarget(cwd, target, force = false) {
  const { rootReal } = assertHandoffTarget(cwd, target, force);
  const parent = path.dirname(target);
  assertExistingAncestorInside(rootReal, parent);
  await mkdir(parent, { recursive: true });
  assertParentInside(rootReal, parent);
}

function assertHandoffTarget(cwd, target, force = false) {
  const root = path.resolve(cwd);
  const rootReal = realPathOrResolve(root);
  const relative = path.relative(root, target);
  if (!isInsidePath(root, target)) {
    throw new Error("Handoff output must stay inside the project directory.");
  }
  if (relative === "AGENTS.md") {
    throw new Error("Refusing to write handoff into AGENTS.md. Use a standalone handoff file.");
  }
  if (existsSync(target)) {
    if (lstatSync(target).isSymbolicLink()) {
      throw new Error(`Refusing to overwrite symlink handoff target: ${relative}`);
    }
    if (!force) {
      throw new Error(`Refusing to overwrite existing handoff without --force: ${relative}`);
    }
  }
  return { root, rootReal, relative };
}

function assertExistingAncestorInside(rootReal, parent) {
  const ancestor = nearestExistingPath(parent);
  const real = realPathOrResolve(ancestor);
  if (!isInsidePath(rootReal, real)) {
    throw new Error("Handoff output parent resolves outside the project directory.");
  }
}

function assertParentInside(rootReal, parent) {
  const real = realpathSync(parent);
  if (!isInsidePath(rootReal, real)) {
    throw new Error("Handoff output parent resolves outside the project directory.");
  }
}

function nearestExistingPath(target) {
  let current = target;
  while (!existsSync(current)) {
    const next = path.dirname(current);
    if (next === current) return current;
    current = next;
  }
  return current;
}

function isInsidePath(parent, child) {
  const relative = path.relative(parent, child);
  return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
}

function realPathOrResolve(target) {
  try {
    return realpathSync(target);
  } catch {
    return path.resolve(target);
  }
}

function git(cwd, args) {
  try {
    return execFileSync("git", args, {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"]
    });
  } catch {
    return undefined;
  }
}

export {
  DEFAULT_HANDOFF_FILE,
  collectHandoffContext,
  createHandoff,
  generateHandoff
};
